%YAML:1.0
---
numberOfClasses: 5
gtImagesPath: /home/pcpj/Classic-Supervised-Classifiers-for-Semantic-Segmentation/data/images/
gtPath: /home/pcpj/Classic-Supervised-Classifiers-for-Semantic-Segmentation/data/gt/
#annotationsImagesPath: /home/pcpj/Classic-Supervised-Classifiers-for-Semantic-Segmentation/data/images/
#annotationsPath: /home/pcpj/Classic-Supervised-Classifiers-for-Semantic-Segmentation/data/anotations/
